version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: proyecto-bdd
    environment:
      POSTGRES_USER: develop
      POSTGRES_PASSWORD: develop
      POSTGRES_DB: develop
    ports:
      - "50000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: